{{- /*
Copyright 2024 New Vector Ltd

SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
*/ -}}
{{- with .Values.elementWeb -}}
{{- if .enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
{{- with .ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "element-io.element-web.labels" (dict "context" . "root" $) | nindent 4 }}
  name: {{ $.Release.Name }}-element-web
  namespace: {{ $.Release.Namespace }}
spec:
{{- if .ingress.tlsSecret }}
  tls:
  - hosts:
    - {{ required "elementWeb.ingress.host is required" .ingress.host | quote }}
    secretName: {{ .ingress.tlsSecret | quote }}
{{- end }}
{{- with .ingress.className }}
  ingressClassName: {{ . | quote }}
{{- end }}
  rules:
  - host: {{ .ingress.host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $.Release.Name }}-element-web
            port:
              number: 80
{{- end }}
{{- end }}
