# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

## Values file containing minimal values for components that are enabled by default only

global:
  ess:
    server_name: ess.localhost

elementWeb:
  ess:
    serverName: ess.localhost

  ingress:
    host: element.ess.localhost

synapse:
  synapse:
    ingress:
      host: synapse.ess.localhost

    registrationSharedSecret:
      value: CHANGEME-ooWo6jeidahhei3Hae0eer9U
    macaroon:
      value: CHANGEME-eek3Eigoh8ux8laeTingeej1
    signingKey:
      value: ed25519 0 bNQOzBUDszff7Ax81z6w0uZ1IPWoxYaazT7emaZEfpw

    postgres:
      host: ess-postgres
      user: synapse_user
      database: synapse
      password:
        secret: ess-postgres
        secretKey: password
