# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

serverName: ess.localhost

elementWeb:
  enabled: false

synapse:
  ingress:
    host: synapse.ess.localhost

  registrationSharedSecret:
    value: CHANGEME-ooWo6jeidahhei3Hae0eer9U
  macaroon:
    value: CHANGEME-eek3Eigoh8ux8laeTingeej1
  signingKey:
    value: ed25519 0 bNQOzBUDszff7Ax81z6w0uZ1IPWoxYaazT7emaZEfpw

  postgres:
    host: ess-postgres
    user: synapse_user
    database: synapse
    password:
      secret: ess-postgres
      secretKey: password

wellKnownDelegation:
  enabled: false
