# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

serverName: ess.localhost

initSecrets:
  enabled: false

elementWeb:
  enabled: false

matrixAuthenticationService:
  enabled: false

haproxy:
  annotations:
    checkov.io/skip1: CKV_K8S_11=We deliberately don't set CPU limits. Pod is BestEffort not Guaranteed
    checkov.io/skip2: CKV_K8S_43=No digests
    checkov.io/skip3: CKV2_K8S_6=No network policy yet

synapse:
  ingress:
    host: synapse.ess.localhost

  registrationSharedSecret:
    value: CHANGEME-ooWo6jeidahhei3Hae0eer9U
  macaroon:
    value: CHANGEME-eek3Eigoh8ux8laeTingeej1
  signingKey:
    value: ed25519 0 bNQOzBUDszff7Ax81z6w0uZ1IPWoxYaazT7emaZEfpw

  postgres:
    host: ess-postgres
    user: synapse_user
    database: synapse
    password:
      secret: ess-postgres
      secretKey: password

  annotations:
    checkov.io/skip1: CKV_K8S_11=We deliberately don't set CPU limits. Pod is BestEffort not Guaranteed
    checkov.io/skip2: CKV_K8S_43=No digests
    checkov.io/skip3: CKV2_K8S_6=No network policy yet

  workers:
    appservice:
      enabled: true
    client-reader:
      enabled: true
    event-persister:
      enabled: true
  redis:
    annotations:
      checkov.io/skip1: CKV_K8S_11=We deliberately don't set CPU limits. Pod is BestEffort not Guaranteed
      checkov.io/skip2: CKV_K8S_43=No digests
      checkov.io/skip3: CKV2_K8S_6=No network policy yet

wellKnownDelegation:
  enabled: false
