# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

# This value file is not complete on its own.
# It is a mixin to be used with other values file to enable
# usage of the test cluster

element-web:
  ingress:
    tlsSecret: ess-selfsigned

synapse:
  ingress:
    tlsSecret: ess-selfsigned
