# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

{{- if .Values.haproxy.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.haproxy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "element-io.synapse.haproxy.labels" . | nindent 4 }}
  name: {{ include "element-io.synapse.haproxy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: false
{{- end }}
