{{- /*
Copyright 2024 New Vector Ltd

SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
*/ -}}

{{- with .Values.synapse -}}
{{- if .enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "element-io.synapse.haproxy.labels" (dict "global" $ "context" .haproxy) | nindent 4 }}
  name: {{ $.Release.Name }}-synapse-haproxy
  namespace: {{ $.Release.Namespace }}
data:
  haproxy.cfg: |
    {{- tpl ($.Files.Get "configs/haproxy/haproxy.cfg.tpl") (dict "global" $ "context" .) | nindent 4 }}
  path_map_file: |
    # A map file that is used in haproxy config to map from matrix paths to the
    # named backend. The format is: path_regexp backend_name

    {{ $enabledWorkerTypes := keys ((include "element-io.synapse.enabledWorkers" (dict "global" $ "context" .)) | fromJson) }}
    {{- range $workerType := $enabledWorkerTypes | sortAlpha }}
    {{- $workersPaths := (include "element-io.synapse.process.workerPaths" (dict "global" $ "context" (dict "workerType" $workerType "enabledWorkerTypes" $enabledWorkerTypes))) | fromJsonArray }}
    {{- if len $workersPaths }}
    # {{ $workerType }}
    {{- range $path := $workersPaths }}
    {{ $path }} {{ $workerType }}
    {{- end }}
    {{ end }}
    {{- end }}
  path_map_file_get: |
    # A map file that is used in haproxy config to map from matrix paths to the
    # named backend. The format is: path_regexp backend_name
    {{ if dig "client-reader" "enabled" false .workers }}
    ^/_matrix/client/(api/v1|r0|v3|unstable)/pushrules/ client-reader
    {{- end }}
  429.http: |
    HTTP/1.0 429 Too Many Requests
    Cache-Control: no-cache
    Connection: close
    Content-Type: text/html
    access-control-allow-origin: *
    access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS
    access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, Authorization

    <html><body><h1>429 Too Many Requests</h1>
    No server is available to handle this request.
    </body></html>
{{- end -}}
{{- end -}}
