# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "element-io.synapse.labels" $ | nindent 4 }}
  name: {{ .Release.Name }}-synapse
  namespace: {{ .Release.Namespace }}
data:
  01-homeserver-underrides.yaml: |
    {{- include "element-io.synapse.config.shared-underrides" . | nindent 4  }}
{{- /*02 files are user provided in Helm values and end up in the Secret*/}}
{{- /*03 files are user provided as secrets rather than directly in Helm*/}}
  04-homeserver-overrides.yaml: |
    {{- include "element-io.synapse.config.shared-overrides" . | nindent 4 }}
  05-main.yaml: |
    {{- include "element-io.synapse.config.processSpecific" (dict "processType" "main" "Values" .Values) | nindent 4 }}
{{- range $workerType, $workerDetails := (include "element-io.synapse.enabledWorkers" $) | fromJson }}
  05-{{ $workerType }}.yaml: |
    {{- include "element-io.synapse.config.processSpecific" (dict "processType" $workerType "Values" $.Values) | nindent 4 }}
{{- end }}
  log_config.yaml: |
    # Copyright 2024 New Vector Ltd
    #
    # SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
    version: 1

    formatters:
      precise:
        format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'

    handlers:
      console:
        class: logging.StreamHandler
        formatter: precise

    loggers:
    {{- /*
    Increasing synapse.storage.SQL past INFO will log access tokens. Putting in the values default will mean it gets
    nuked if an override is set and then if the root level is increased to debug, the access tokens will be logged.
    Putting here means it is an explicit customer choice to override it.
    */}}
    {{- range $logger, $level := merge dict .Values.logging.levelOverrides (dict "synapse.storage.SQL" "INFO") }}
      {{ $logger }}:
        level: "{{ $level }}"
    {{- end }}

    root:
      level: "{{ .Values.logging.rootLevel }}"
      handlers:
      - console

    disable_existing_loggers: false
  render_config_with_secrets.py: |
    {{- ($.Files.Get "configs/synapse/render_config_with_secrets.py") | nindent 4 }}
