{{- /*
Copyright 2024 New Vector Ltd

SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
*/ -}}

{{- with .Values.synapse -}}
{{- if .enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "element-io.synapse.haproxy.labels" (dict "root" $ "context" .haproxy) | nindent 4 }}
  name: {{ $.Release.Name }}-synapse-haproxy
  namespace: {{ $.Release.Namespace }}
spec:
  type: {{ .ingress.service.type | default $.Values.ingress.service.type }}
  ports:
  - name: haproxy-http
    port: 8008
    targetPort: haproxy-http
  - name: haproxy-403
    port: 8009
    targetPort: haproxy-403
  - name: haproxy-metrics
    port: 8405
    targetPort: haproxy-metrics
  selector:
    app.kubernetes.io/instance: "{{ $.Release.Name }}-synapse-haproxy"
{{- end -}}
{{- end -}}
