{{- /*
Copyright 2024 New Vector Ltd

SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
*/ -}}
{{- with .Values.elementWeb -}}
{{- if .enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
{{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "element-io.element-web.labels" (dict "root" $ "context" .) | nindent 4 }}
  name: {{ $.Release.Name }}-element-web
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name }}-element-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        {{- include "element-io.element-web.labels" (dict "root" $ "context" .) | nindent 8 }}
        k8s.element.io/confighash: "{{ include (print $.Template.BasePath "/element-web/configmap.yaml") $ | sha1sum }}"
        k8s.element.io/nginxhash: "{{ include (print $.Template.BasePath "/element-web/nginx_configmap.yaml") $ | sha1sum }}"
{{- with .annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
{{- end }}
    spec:
{{- if gt (.replicas | int) 1 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - "{{ $.Release.Name }}-element-web"
              topologyKey: kubernetes.io/hostname
{{- end }}
      automountServiceAccountToken: false
      serviceAccountName: {{ include "element-io.element-web.serviceAccountName" (dict "root" $ "context" .) }}
{{- include "element-io.ess-library.pods.pullSecrets" (dict "root" $ "context" .image) | indent 6 }}
{{- with .podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- include "element-io.ess-library.pods.topologySpreadConstraints" (dict "root" $ "context" (dict "instanceSuffix" "element-web" "deployment" true "topologySpreadConstraints" .topologySpreadConstraints)) | indent 6 }}
      containers:
      - name: element-web
{{- with .image -}}
{{- if .digest }}
        image: "{{ .registry }}/{{ .repository }}@{{ .digest }}"
        imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" }}
{{- else }}
        image: "{{ .registry }}/{{ .repository }}:{{ .tag | default $.Chart.AppVersion }}"
        imagePullPolicy: {{ .pullPolicy | default "Always" }}
{{- end }}
{{- end }}
{{- with .containersSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
{{- end }}
        ports:
        - containerPort: 8080
          name: element
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: element
            scheme: HTTP
          periodSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: element
            scheme: HTTP
          periodSeconds: 3
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: element
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 3
{{- with .resources }}
        resources:
          {{- toYaml . | nindent 10 }}
{{- end }}
        volumeMounts:
        - mountPath: /app/config.json
          name: config
          readOnly: true
          subPath: config.json
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config
          readOnly: true
          subPath: nginx.conf
        - mountPath: /tmp
          name: nginx-tmp
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ $.Release.Name }}-element-web
        name: config
      - configMap:
          defaultMode: 420
          name: {{ $.Release.Name }}-element-web-nginx
        name: nginx-config
      - emptyDir:
          medium: Memory
        name: nginx-tmp
{{- end }}
{{- end }}
