# Copyright 2025 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

matrixAuthenticationService:
  additional:
    0000-matrix-server:
      config: |
        clients:
        - client_id: "0000000000000000000SYNAPSE"
          client_auth_method: client_secret_basic
          client_secret: CHANGEME-eiv6wae8shooPhie4ief8ru2egahbah0
        matrix:
          homeserver: "external.localhost
          secret: jaix6Am9Shut7zeiduu7ua5maengag3o
          endpoint: https://syn.external.localhost
