

# Copyright 2025 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

matrixRTC:
  livekitAuth:
    keysYaml:
      value: |
        CHANGEME-ooShei6Aebe0mesheicooCoo8Juuceke: CHANGEME-deiv8au0poecheamusohZe7Fil9pogu4
