# Copyright 2025 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

matrixRTC:
  enabled: true
  ingress:
    host: mrtc.ess.localhost

  extraEnv:
    - name: LIVEKIT_URL
      value: wss://demo.livekit.cloud

  sfu:
    enabled: false
