

# Copyright 2025 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

matrixRTC:
  livekitAuth:
    key: CHANGEME-oolahd9xooshohSh5IeQu1natheur1oo
    secret:
      value: CHANGEME-gohseengahch9pheedi5OomeHea6maem
