# Copyright 2025 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

elementWeb:
  enabled: true

matrixAuthenticationService:
  enabled: true

matrixRTC:
  enabled: true

synapse:
  enabled: true

wellKnownDelegation:
  enabled: true
