# Copyright 2025 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

synapse:
  postgres:
    host: your-db-host.tld
    port: 5432
    user: your-synapse-user
    password:
      value: your-synapse-user-password
    database: your-synapse-database-name
    sslMode: prefer

matrixAuthenticationService:
  postgres:
    host: your-db-host.tld
    port: 5432
    user: your-matrix-auth-service-user
    password:
      value: your-matrix-auth-service-user-password
    database: your-matrix-auth-service-database-name
    sslMode: prefer
