# Copyright 2025 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

synapse:
  registrationSharedSecret:
    value: CHANGEME-ooWo6jeidahhei3Hae0eer9U
  macaroon:
    value: CHANGEME-eek3Eigoh8ux8laeTingeej1
  signingKey:
    value: ed25519 0 bNQOzBUDszff7Ax81z6w0uZ1IPWoxYaazT7emaZEfpw
